// <auto-generated />
using BRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BRMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("BRMS.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId");

                    b.HasIndex("RecordedBy");

                    b.HasIndex("ResidentId");

                    b.HasIndex("EventId", "ResidentId")
                        .IsUnique();

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableAffected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.BarangaySettings", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("BarangayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretaryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("BarangaySettings", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.BlotterEntry", b =>
                {
                    b.Property<int>("BlotterEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlotterNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComplainantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComplainantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FiledAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FiledBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncidentDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<string>("RespondentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Open");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlotterEntryId");

                    b.HasIndex("BlotterNumber")
                        .IsUnique();

                    b.HasIndex("ComplainantId");

                    b.HasIndex("FiledBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("BlotterEntries", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.ClearanceRequest", b =>
                {
                    b.Property<int>("ClearanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("ClearanceId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("ResidentId");

                    b.ToTable("ClearanceRequests", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseholdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurokId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HouseholdId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HeadResidentId");

                    b.HasIndex("HouseholdNumber")
                        .IsUnique();

                    b.HasIndex("PurokId");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.InteractionLog", b =>
                {
                    b.Property<int>("InteractionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InteractionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractionLogId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ResidentId");

                    b.ToTable("InteractionLogs", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.Purok", b =>
                {
                    b.Property<int>("PurokId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PurokId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Puroks", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<string>("CivilStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurokId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResidencySince")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.HasKey("ResidentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("PurokId");

                    b.ToTable("Residents", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BRMS.Models.Attendance", b =>
                {
                    b.HasOne("BRMS.Models.Event", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BRMS.Models.User", "RecordedByUser")
                        .WithMany("RecordedAttendances")
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BRMS.Models.Resident", "Resident")
                        .WithMany("Attendances")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("RecordedByUser");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("BRMS.Models.AuditLog", b =>
                {
                    b.HasOne("BRMS.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BRMS.Models.BarangaySettings", b =>
                {
                    b.HasOne("BRMS.Models.User", "UpdatedByUser")
                        .WithMany("UpdatedBarangaySettings")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("BRMS.Models.BlotterEntry", b =>
                {
                    b.HasOne("BRMS.Models.Resident", "Complainant")
                        .WithMany("BlotterEntries")
                        .HasForeignKey("ComplainantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BRMS.Models.User", "FiledByUser")
                        .WithMany("FiledBlotterEntries")
                        .HasForeignKey("FiledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BRMS.Models.User", "UpdatedByUser")
                        .WithMany("UpdatedBlotterEntries")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Complainant");

                    b.Navigation("FiledByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("BRMS.Models.ClearanceRequest", b =>
                {
                    b.HasOne("BRMS.Models.User", "ProcessedByUser")
                        .WithMany("ProcessedClearanceRequests")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BRMS.Models.Resident", "Resident")
                        .WithMany("ClearanceRequests")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("BRMS.Models.Event", b =>
                {
                    b.HasOne("BRMS.Models.User", "CreatedByUser")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("BRMS.Models.Household", b =>
                {
                    b.HasOne("BRMS.Models.User", "CreatedByUser")
                        .WithMany("CreatedHouseholds")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BRMS.Models.Resident", "HeadResident")
                        .WithMany("HeadedHouseholds")
                        .HasForeignKey("HeadResidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BRMS.Models.Purok", "Purok")
                        .WithMany("Households")
                        .HasForeignKey("PurokId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("HeadResident");

                    b.Navigation("Purok");
                });

            modelBuilder.Entity("BRMS.Models.InteractionLog", b =>
                {
                    b.HasOne("BRMS.Models.User", "CreatedByUser")
                        .WithMany("CreatedInteractionLogs")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BRMS.Models.Resident", "Resident")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("BRMS.Models.Resident", b =>
                {
                    b.HasOne("BRMS.Models.User", "CreatedByUser")
                        .WithMany("CreatedResidents")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BRMS.Models.Household", "Household")
                        .WithMany("Residents")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BRMS.Models.Purok", "Purok")
                        .WithMany("Residents")
                        .HasForeignKey("PurokId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Household");

                    b.Navigation("Purok");
                });

            modelBuilder.Entity("BRMS.Models.User", b =>
                {
                    b.HasOne("BRMS.Models.Resident", "Resident")
                        .WithMany("Users")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BRMS.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BRMS.Models.Event", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("BRMS.Models.Household", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("BRMS.Models.Purok", b =>
                {
                    b.Navigation("Households");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("BRMS.Models.Resident", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("BlotterEntries");

                    b.Navigation("ClearanceRequests");

                    b.Navigation("HeadedHouseholds");

                    b.Navigation("InteractionLogs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BRMS.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BRMS.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedEvents");

                    b.Navigation("CreatedHouseholds");

                    b.Navigation("CreatedInteractionLogs");

                    b.Navigation("CreatedResidents");

                    b.Navigation("FiledBlotterEntries");

                    b.Navigation("ProcessedClearanceRequests");

                    b.Navigation("RecordedAttendances");

                    b.Navigation("UpdatedBarangaySettings");

                    b.Navigation("UpdatedBlotterEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
